Repository TeamCaleFIT/calefit-BE, pull requests merged in 2022-08, with the labels that each got.

#8 초기 Entity 및 값타입 작성
  src/docs/asciidoc/index.adoc
  src/main/java/com/calefit/common/domain/BaseTime.java
  src/main/java/com/calefit/crew/domain/Description.java
  src/main/java/com/calefit/crew/domain/Image.java
  src/main/java/com/calefit/crew/domain/Name.java
  src/main/java/com/calefit/crew/entity/Crew.java
  src/main/java/com/calefit/crew/entity/CrewApplication.java
  src/main/java/com/calefit/member/domain/BodyInfo.java
  src/main/java/com/calefit/member/domain/Email.java
  src/main/java/com/calefit/member/domain/NickName.java
  src/main/java/com/calefit/member/domain/Password.java
  src/main/java/com/calefit/member/entity/Member.java
Labels: Chore

#9 초기 Entity 및 값타입 작성 (피오)
  src/main/java/com/calefit/inbody/domain/BodyComposition.java
  src/main/java/com/calefit/inbody/entity/Inbody.java
  src/main/java/com/calefit/template/entity/Template.java
  src/main/java/com/calefit/template/entity/TemplateWorkoutSet.java
  src/main/java/com/calefit/workout/entity/Schedule.java
  src/main/java/com/calefit/workout/entity/Term.java
  src/main/java/com/calefit/workout/entity/Workout.java
  src/main/java/com/calefit/workout/entity/WorkoutLog.java
Labels: Feature

#12 Feat: 엔티티 연관관계 추가
  src/main/java/com/calefit/template/entity/Template.java
  src/main/java/com/calefit/workout/entity/Schedule.java
Labels: Feature

#13 Feat: 엔티티 연관관계 수정
  src/main/java/com/calefit/crew/entity/Crew.java
  src/main/java/com/calefit/crew/entity/CrewApplication.java
  src/main/java/com/calefit/member/entity/Member.java
Labels: Feature

#17 Feat: 공통 응답 클래스 생성
  src/main/java/com/calefit/common/base/BaseResponse.java
  src/main/java/com/calefit/common/base/BaseTime.java
  src/main/java/com/calefit/common/base/CodeAndMessages.java
  src/main/java/com/calefit/common/base/ResponseCodeAndMessages.java
  src/main/java/com/calefit/common/entity/CommonResponseEntity.java
Labels: Feature, Refactor

#18 Feat: Crew 테스트를 제외한 CRUD API 구현
  build.gradle
  src/main/java/com/calefit/CalefitApplication.java
  src/main/java/com/calefit/common/dto/CommonDtoList.java
  src/main/java/com/calefit/crew/CrewController.java
  src/main/java/com/calefit/crew/CrewRepository.java
  src/main/java/com/calefit/crew/CrewService.java
  src/main/java/com/calefit/crew/domain/Description.java
  src/main/java/com/calefit/crew/domain/Image.java
  src/main/java/com/calefit/crew/domain/Name.java
  src/main/java/com/calefit/crew/dto/CrewCreateRequest.java
  src/main/java/com/calefit/crew/dto/CrewDeleteRequest.java
  src/main/java/com/calefit/crew/dto/CrewDetailedResponse.java
  src/main/java/com/calefit/crew/dto/CrewSearchResponse.java
  src/main/java/com/calefit/crew/dto/CrewUpdateRequest.java
  src/main/java/com/calefit/crew/entity/Crew.java
  src/main/java/com/calefit/crew/exception/NotFoundCrewException.java
  src/main/java/com/calefit/member/MemberRepository.java
  src/main/java/com/calefit/member/domain/CrewInfo.java
  src/main/java/com/calefit/member/domain/Email.java
  src/main/java/com/calefit/member/domain/NickName.java
  src/main/java/com/calefit/member/domain/Password.java
  src/main/java/com/calefit/member/entity/Member.java
  src/main/resources/application.yml
  src/test/java/com/calefit/crew/CrewControllerTest.java
Labels: Feature
